import Head from 'next/head';
import { Flex } from '@chakra-ui/react';
import { trpc } from './utils/trpc';
import { useEffect, useMemo } from 'react';

export default function Home() {
  const { data, isLoading } = trpc.getUserById.useQuery('hello');

  useEffect(() => {
    console.log(data);
  }, [data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>lol</Flex>
    </>
  );
}
